[build]
  command = "npm install -g autoprefixer postcss tailwindcss && npm install autoprefixer postcss tailwindcss && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"